spring:
  datasource:
#     h2:
#        url: jdbc:h2:tcp://localhost/~/test
#        driver-class-name: org.h2.Driver
#        username: sa
#        password: 1234
#
#    mysql
    url: jdbc:mysql://localhost:3306/sellhappiness
    username: ssafy
    password: ssafy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.type: trace

# iamport key
iamport:
  api:
    key: 3706241182160536
    secret: sTaPEyfRzvhanHocyVkTsgzw6u3yyGzwIQUSpjFYH14HWqA13vBrkmMsMIfeqJpxXhpXFmpPn9Loxbnk

oauth:
  google:
    client-id: 651679120216-gedguefmg8lgjhi8vul42c48r9305mol.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8080/login/oauth/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo